### ISSUE TITLE
[question] how do you mock serde::Deserialize & serde::Serialize?

### ISSUE THREAD

**Issue by jjmark15** [asomers/mockall#158]
I am trying to mock a struct that implements a the `serde::Deserialize` trait. I tried imitating the example in https://github.com/asomers/mockall/blob/master/mockall/tests/mock_generic_method_with_lifetime_parameter.rs. 

```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Thing {}

impl Thing {}

#[cfg(test)]
mod mocks {
    use mockall::{mock, predicate::*};
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    mock! {
        pub Thing {
        }

        trait Serialize {
            fn serialize<S: Serializer>(&self, serializer: S) -> Result<String, anyhow::Error>;
        }

        trait Deserialize {
            fn deserialize<D: Deserializer>(deserializer: D) -> Result<Self, anyhow::Error>;
        }
    }
}
```

**Comment by asomers** [comment]
Wow, this is surprisingly hard!  The problem is that `Serializer` isn't `'static`, and the definition of `Serialize::serialize` doesn't require that `S` be `'static`.  When mocking generic methods, Mockall requires that the generic type be `'static` so it can implement [`Any`](https://doc.rust-lang.org/std/any/trait.Any.html).  There's really no getting around that requirement without sacrificing tons of Mockall's functionality.  I may be able to come up with a workaround involving the erased_serde crate.  I'll try when I get some time.

**Comment by jjmark15** [comment]
Ah, thank you so much for investigating. It would definitely be a very useful example of mockall for me

**Comment by asomers** [comment]
`erased_serde` didn't work for various reasons.  Specialization (a nightly feature) didn't work either, because you can't specialize on a lifetime.  I'll commit a slightly hacky workaround soon.

**Comment by asomers** [comment]
Here's the finished example of how to mock Serde traits with Mockall.
https://github.com/asomers/mockall/blob/master/mockall/examples/serde.rs
