### ISSUE TITLE
Can't create a str predicate using String without static lifetime

### ISSUE THREAD

**Issue by gmcmanus** [asomers/mockall#231]
If a trait takes a `&str` as an argument, it seems it isn't possible to add a `with` predicate using a String value - it complains that the borrowed value needs to have a static lifetime. Using a &str literal works, but this isn't always possible (e.g. in generative testing).

Example:

```rust
use mockall::automock;
use mockall::predicate::eq;

#[automock]
trait StrTrait {
    fn f(&self, s: &str);
}

fn mock_f() {
    let mut mock_str_trait = MockStrTrait::new();

    // this works
    mock_str_trait
        .expect_f()
        .with(eq(""))
        .return_const(());

    // this doesn't
    let s = String::new();
    mock_str_trait
        .expect_f()
        .with(eq(&*s))
        .return_const(());
}
```

This produces the following error:
```
error[E0597]: `s` does not live long enough
  --> src\lib.rs:22:20
   |
22 |         .with(eq(&*s))
   |               -----^-
   |               |    |
   |               |    borrowed value does not live long enough
   |               argument requires that `s` is borrowed for `'static`
23 |         .return_const(());
24 | }
   | - `s` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

**Comment by asomers** [comment]
That's right, Predicates must be `'static`.  That's because when you set an expectation, the predicate must be stored within the mock object.  Theoretically I could loosen the requirement so that a Predicate merely had to outlive the mock, but that would be a lot of work (and notice that in your example, `s`'s lifetime isn't sufficient, because it's declared after the mock object).

If you are unable to create `'static` Strings for your tests, then you should try matching with `withf`, like this:
```rust
let expected = String::new();
mock_str_trait
    .expect_f()
    .withf(move |s| s == &expected)
    .return_const(());
```
This issue is similar to https://github.com/asomers/mockall/issues/58 .

**Comment by gmcmanus** [comment]
I was able to get something working using `withf` and `move` - thanks for your help, my problem is solved now!

I do wonder whether we could keep the `'static` restriction, but somehow move a `String` into `eq` to create the required predicate? e.g. if the trait method takes a `&String` instead of a `&str` then the below works. Could something similar could be made to work in the original example too? The main benefit is it is more ergonomic to use `with` than `withf`.

```rust
use mockall::automock;
use mockall::predicate::eq;

#[automock]
trait StrTrait {
    fn f(&self, s: &String);
}

fn mock_f() {
    let mut mock_str_trait = MockStrTrait::new();

    let s = String::new();
    mock_str_trait
        .expect_f()
        .with(eq(s))
        .return_const(());
}
```

**Comment by asomers** [comment]
Glad that it worked for you!  Yes, it might be possible, for common `Deref` types like `&str`, for the expectation to take the owned type like `String`.  Emphasis on the "might".  In fact, it might be best to make such a change to the [predicates](https://docs.rs/predicates/1.0.5/predicates/index.html) crate, rather than to Mockall directly.
