### ISSUE TITLE
Mocking without attribute on implementation 

### ISSUE THREAD

**Issue by falconmick** [asomers/mockall#257]
Hey all

I’ve been looking for somthing that would let me achieve my mocking needs and this library looks amazing.

the only issue I’m having with it so far is all the docs show the mockall attribute attached to the real implementation.

typically in other languages I would not include any code (even if optimisation remove it on build) that is to do with testing in my actual codebase and all testing code would live in the seperate test files. So really this isn’t a problem with mockall, but more a problem with my compulsion to want to keep tests as far away from code as possible

is this possible with automock? If not does production build fully remove this attribute? Sorry if any of these questions are silly, still very new to rust and I’m trying to get my usual dev flow working still

**Comment by asomers** [comment]
The `#[automock]` attribute doesn't by itself do anything special based on debug/release or test/non-test builds.  That's why the most common way to use it is like this:
```rust
#[cfg_attr(test, automock)]
trait Foo {
...
}
```
That way the mock code will only get compiled for your unit tests.

But if you really want 100% of the mocking code to live in separate files, that's possible too.  It's just less convenient, because you have to define the mocked code twice.  It's also a little error-prone, because when you change the real code you might forget to change the mocks.  To do this, use [mock!](https://docs.rs/mockall/0.9.1/mockall/macro.mock.html) instead of `#[automock]`.

**Comment by falconmick** [comment]
As much as I dislike test related code in my implementation, I think repeating yourself is not a better option. Thanks for clarifying that and I think the cfg_attr is the best solution.

I was hoping I could find somthing like how in c#’s NSubstitute package where you define a new instances of a stub that the testing framework made that implements the interface. But this is pretty damn close to what I need

**Comment by asomers** [comment]
Glad to help.
