### ISSUE TITLE
Mocking static function is different tests

### ISSUE THREAD

**Issue by mikeymikeymikeymikey** [asomers/mockall#267]
I'm trying to mock a static function from multiple tests, and there seems to be some race conditions which make the tests flaky.

I tried to use `serial_tests` to fix this, with no success.

The tests are along these lines (heavily inspired by #240):

```rust
fn foo(i: u32) -> bool {
    return i == 2;
}

fn setup_expectations() -> Vec<Box<dyn Drop>> {
    let mut expectations: Vec<Box<dyn Drop>> = vec![];
    let ctx_foo = Box::new(foo_context());
    ctx_foo
        .expect()
        .withf(|i| *i == 2 || *i == 3)
        .returning(|i| i == 2);

    expectations.push(ctx_foo);
    expectations;
}

#[test]
fn test_foo() {
    let _expectations = setup_expectations();

    let res = foo(2);
    assert!(res);
}

#[test]
fn test_foo() {
    let _expectations = setup_expectations();

    let res = foo(3);
    assert!(!res);
}
```

Obviously not the exact code, but this is the basic concept.

When running each test individually they succeed.
Run all the tests together causes errors such as `No matching expectation found`, `called Result::unwrap()` on an `Err` value: "PoisonError..."` and `trying to access wrapped value in fragile container from incorrect thread`.

**Comment by asomers** [comment]
Since `foo` is static, its expectations are, too.  You can't safely use them from multiple tests at the same time.  You'll probably find that your tests pass if you run then single-threaded, like `cargo test -- --test-threads=1`.  But better would be to protect them with a Mutex.  See for example `BAR_MTX` in https://github.com/asomers/mockall/blob/master/mockall/tests/mock_struct_with_static_method.rs .

**Comment by mikeymikeymikeymikey** [comment]
Thanks for the help!
