### ISSUE TITLE
`new` method not generated while mocking trait that includes a `new` method

### ISSUE THREAD

**Issue by winterqt** [asomers/mockall#334]
```rust
#[mockall::automock]
trait X {
    fn new() -> Self;
}
```

The only `new` method that exists on the generated `MockX` struct is the `new` from the trait itself. The `Default` implementation is created, however.

If I'm understanding the documentation (and the code) correctly, this should only happen when mocking structs, not traits.

`mockall` version: 0.10.2

**Comment by asomers** [comment]
Hm, there should be a `new` method generated.  Why do you think there isn't?

**Comment by winterqt** [comment]
I'm confused too, yeah.

Here's a reproducible example that works for me:

```rust
#[mockall::automock]
trait X {
    fn new(a: u8) -> Self;
}

fn a() {
    MockX::new();
}
```

```rust
error[E0061]: this function takes 1 argument but 0 arguments were supplied
   |
   |         MockX::new();
   |         ^^^^^^^^^^-- supplied 0 arguments
   |         |
   |         expected 1 argument
   |
note: associated function defined here
   |
   |         fn new(a: u8) -> Self;
   |            ^^^
```

**Comment by asomers** [comment]
So I actually changed that behavior on purpose in #3 , but didn't update all of the docs.  I could change it back.  However, then users would need to call `<MockFoo as Foo>::new()` instead of `MockFoo::new()`, which is annoying.  Do you have a really good reason why it's better to use `new` as a default constructor instead of `default`?  If not I won't make the change.

**Comment by winterqt** [comment]
Yeah, I don't either, the docs just confused me.

Thanks for the clarification!
