### ISSUE TITLE
Static method with associated types not working as expected

### ISSUE THREAD

**Issue by winterqt** [asomers/mockall#336]
```rust
#[mockall::automock(type A=();)]
trait X {
    type A;

    fn new(abc: Self::A) -> Self;
}

#[test]
fn aaa() {
    MockX::new_context()
        .expect()
        .returning(|_| MockX::default());

    MockX::new(());
}
```

```
MockX::new(?): No matching expectation found
```

I'm not sure if I'm just doing something wrong, or if I'm understanding the example wrong. But, as far as I know, this *should* work?

**Comment by asomers** [comment]
You're suffering from a lifetime problem.  `new_context` creates a `Context` object.  When they drop, `Context` objects implicitly `checkpoint`.  If you had specified a `times` on that expectation, the test would've failed because the expectation wasn't satisfied by the time the context dropped.
https://docs.rs/mockall/0.10.2/mockall/#context-checkpoints
Try this instead:
```rust
#[test]
fn aaa() {
    let ctx = MockX::new_context();
    ctx.expect()
        .returning(|_| MockX::default());

    MockX::new(());
}
```

**Comment by winterqt** [comment]
That worked, thank you.
