### ISSUE TITLE
Support async `returning` statement for struct mocks

### ISSUE THREAD

**Issue by DDtKey** [asomers/mockall#359]
Hi there!

I faced with one issue. I wanted to make an async call inside the `returning` statement, however it fails. 

Example:
```rs
struct Test;

#[cfg_attr(test, mockall::automock)]
impl Test {
   async fn create(&self) -> u32 { 1 } 
}

#[tokio::test] 
async fn test() {
     let mock = Test::default();
     mock.expect_create()
            .returning(|_| {
                 tokio::time::sleep(Duration::from_secs(2));
                 1
            });
    // ... test case here
}
```

AFAIK we can use `async_trait` for traits. But for struct I found only one workaround (using `mock!`) and honestly it looks ugly :smiling_face_with_tear:

<details>
<summary>Workaround example</summary>

```rs
struct Test;
impl Test {
   async fn create(&self) -> u32 { 1 } 
}

#[cfg(test)]
mockall::mock! {
    #[derive(Clone)]
    pub Test {
       pub fn create() -> impl std::future::Future<Output = u32> + Send + Sync;
    }
}    

#[tokio::test] 
async fn test() {
     let mock = Test::default();
     mock.expect_create()
            .returning(|_| { Box::pin(async {
                 tokio::time::sleep(Duration::from_secs(2));
                 1
            }});
    // ... test case here
}
```

</details> 

Could you consider adding support for nested async calls inside `returning`? Maybe even a separate `returning_async` fn? 🤔

**Comment by asomers** [comment]
Your workaround is the best way to do it right now (except it's missing an `.await`).  Currently when mocking async functions Mockall excepts the returner to return immediately.  That's convenient for the most common use case.  Unfortunately I don't know of any way to change it that doesn't also encumber all of those common use cases.  Also, I don't see a way to get around the need to `Box` the future, since the callback is stored as a function pointer within the mock object.

**Comment by asomers** [comment]
It's not possible to auto-box under the hood, because Mockall still must store a function pointer to the returning callback, and to do that it needs to know its return type.  The only way for Mockall to autobox would involve a macro, and not sure that would be an improvement over the user doing it.  Something like this:
```rust
my_mock.returning(mockall_async!(|_| Ok(0)));
```

**Comment by DDtKey** [comment]
I meant to add `AsyncExpectations` that store a pointer to a function that returns `impl Future` for example. 
So the following code should works fine 🤔 
```rs
mock.async_expect()
   .returning(|_| async { Ok(0) });
```

**Comment by asomers** [comment]
But `impl Future` isn't a type.  You can't store a function pointer to a function unless you can name its return type.

**Comment by DDtKey** [comment]
These are the details. Look at what code is generated in my workaround.

It can be stored in the following form:
```rs
where MockallF: FnMut() -> ::std::pin::Pin<Box<
    dyn std::future::Future<Output = u32> + Send + Sync>,
> + Send + 'static,
```

**Comment by asomers** [comment]
But that's the type that is _already_boxed_.  Using that requires the user to box the future.

**Comment by DDtKey** [comment]
Anyway, please consider this option:
> 2. Add argument to automock macro, for example automock(wrap_async) and it will expand async fn to ... -> impl Future...

I would really like to avoid the signature boilerplate. If it requires `Box::pin` manually, that's fine

**Comment by asomers** [comment]
In that playground example, the `struct AsyncExpectation` is generic.  It would need to be concrete to be incorporated into Mockall.  Otherwise, the entire mock object must be generic on that parameter.

**Comment by DDtKey** [comment]
Hey!
Feel free to close this issue, I think we've already discussed the key points. Thanks.
