### ISSUE TITLE
Support mocking generic functions with `mock!`?

### ISSUE THREAD

**Issue by andronat** [asomers/mockall#413]
I have the following top level function:
```rust
pub fn new<T: Port>() -> (Inner<T>, Outer<T>) {
  // ... implementation ...
}
```

And ideally I would like to export a mock of this function. Ideally with this signature:
```rust
fn mock_new<T: Port>() -> (MockInner<T>, Outer<T>)
```
Notice the return types. `MockInner<T>` is a type I'm already mocking with `mock!`.

The way I'm currently solving this issue is by including this function in a struct implementation and then use `mock!` like this:
```rust
pub struct A;

impl A {
    pub fn new<T: Port>() -> (Inner<T>, Outer<T>) {
      // ... implementation ...
    }
}

#[cfg(test)]
mock! {
    pub A {
        pub fn new<T: Port>() -> (MockInner<T>, Outer<T>);
    }
}
```
And then of course, I'm using `double` to switch between the two.

I'm wondering if something like this is supported:
```rust
pub fn new<T: Port>() -> (Inner<T>, Outer<T>) {
  // ... implementation ...
}

#[cfg(test)]
mock! {
  pub fn new<T: Port>() -> (MockInner<T>, Outer<T>);    }
}
```
I can see that mackall already supports mocking functions [here](https://docs.rs/mockall/latest/mockall/#modules) and [here](https://docs.rs/mockall/latest/mockall/#foreign-functions). But I'm not sure how can I solve my problem.

**Comment by asomers-ax** [comment]
χαίρε Ἀναστάσιε! So your problem is that you want to mock a free function instead of a struct or module method? Mockall can do that, but you need to put the function inside of a module. 
```rust
#[double]
use something::Inner;
#[automock]
pub mod foo {
    pub fn new(...) {...}
}
```

**Comment by andronat** [comment]
Thanks for the warm welcome @asomers-ax @asomers! 😃 And also thank you for your continuous support!! I took me longer that I thought, but here are my thoughts.

 Indeed you are right with using a module, and indeed I tried it but I kinda failed. Here is what I did exactly:
 ```rust
 #[cfg(test)]
use mockall::automock;

#[cfg(test)]
#[automock()]
pub mod port_gen {
    use mockall_double::double;

    #[double]
    use super::Inner;

    use super::{mpsc, Outer, Port};

    pub fn new<T: Port>() -> (Inner<T>, Outer<T>) {
        let (input_tx, input_rx) = mpsc::channel(T::INPUT_CAPACITY);
        let (output_tx, output_rx) = mpsc::channel(T::OUTPUT_CAPACITY);
        let inner = Inner { tx: output_tx, rx: input_rx }; // This will become Inner::new(output_tx, input_rx)
        let outer = Outer { tx: input_tx, rx: output_rx };
        (inner, outer)
    }
}
 ```
 
 Where `Inner<T>` is:
 ```rust
pub type InnerRx<T> = mpsc::Receiver<Input<T>>;
pub type InnerTx<T> = mpsc::Sender<Output<T>>;

 pub struct Inner<T: Port> {
    pub tx: InnerTx<T>,
    pub rx: InnerRx<T>,
}
```

There are some issues with this approach:
1. Using `#[automock()]` on `mod port_gen` generates a signature of `mock_port_pair::new<T>() -> (Inner<T>, Outer<T>)` instead of the `mock_port_pair::new<T>() -> (MockInner<T>, Outer<T>)` that I need. To solve this, I introduced `#[double]` on `use super::Inner;`. This helped, but it introduced the following problems.
2. By introducing `#[double]` the `new()` function can't compile because of #123. As you can see `Inner` is initialized by fields: `let inner = Inner { tx: output_tx, rx: input_rx };`. To bypassed this, I created a `new()` method on `Inner<T>` with the right arguments. I also included `new()` in the `mock!` of `Inner<T>` (for my `MockInner<T>`). This worked but we will have to change the `new()` method every time we introduce a new field. Maybe supporting #123 is the right path here?
3. After fixing the above, I stumbled upon a third issue on which I'm currently **blocked**. Using `#[automock()]` with the encapsulated `#[double]` results into creating `mock_port_pair::new<T>() -> (MockInner<T>, Outer<T>)` which is exactly what I want, but it also creates `port_pair::new<T>() -> (MockInner<T>, Outer<T>)` which breaks other parts of my code where I don't want to introduce mocking just yet. I don't have a solution for this. I was hopping that maybe `#[double]` could become conditional under `#[automock()]` but I can't find any `#[cfg]` trick to do this. Any suggestions on how to overcome this?

## Conclusion

It feels to me that supporting functions with `mock!()` (or something like `mock_fn!()`) would help such use cases here significantly. As in my first post, the following would be amazing ergonomics, would solve all of my problems:
```
#[cfg(test)]
mock! {
  pub fn new<T: Port>() -> (MockInner<T>, Outer<T>);    }
}
```

I'm not sure if I managed to take such a wrong turn in my approach and I ended up here, or this is indeed an interesting use case. Any comments are more than welcome!

**Comment by asomers** [comment]
1. I see that you're using `#[double]` within a block that's gated by `#[cfg(test)]`.  That's redundant, because `#[double]`'s purpose is to do different things in `test` builds.  So you may as well just remove it and have `use super::MockInner`.
2. No, Mockall will never support struct fields.  Unlike in Python, you can't tell the compiler to do anything special when somebody sets or gets a field.  So there's no way to set expectations, and no way to specify return values.  However, it might be something that you could do if you roll your own custom mock objects.
3. What exactly are you trying to accomplish with mocking, anyway?  Since the `port_gen` module is gated by `#[cfg(test)]`, it clearly doesn't contain any real code.  And even if you did have a `mock_new` function that returns a `MockInner` to contrast with a `new` function that returns an `Inner`, how would you use it?  It wouldn't be useful unless it's used by non-mock code in other parts of your program, which you said you aren't ready for yet.

Although I can't see your entire program, I'm suspecting there might be some layering violations going on.  As a matter of philosophy, mocking works best when the program is divided up into multiple layers.  Each layer's unit tests use a mock version of the lower layer.  A major no-no is trying to use a real struct and its mock version in the same place.  That's a sign of a layering violation.  Here's an example of a well-layered application that uses mocks in its unit tests.
```rust
mod a {
    struct Foo {...}
    #[automock]
    impl Foo {...}

    // No unit tests because there is no underlying mock layer
}

mod b {
    #[double]
    use super::a::Foo;

    struct Bar {...}
    #[automock]
    impl Bar {
        fn new(inner: Foo) -> Self;
        ...
    }

    #[test]
    fn test_something() {
        let mut mock = Foo::new();
        mock.expect_something()
            .return_const(42);
        let bar = Bar::new(mock);
        bar.do_something();
    }
}

mod c {
    #[double]
    use super::b::Bar;

    struct Baz {...}
    #[automock]
    impl Baz {
        fn new(inner: Bar) -> Self;
        ...
    }

    #[test]
    fn test_something() {
        let mut mock = Bar::new();
        mock.expect_something()
            .return_const(42);
        let baz = Baz::new(mock);
        baz.do_something();
    }
}
```

**Comment by andronat** [comment]
Apologies! Quick fix, there is no `#[cfg(test)]` on `new()`. Indeed this part of the code is actually used in other places.

**Comment by asomers** [comment]
Closing for lack of feedback.  Reopen if your question isn't fully answered.
