### ISSUE TITLE
Poisoned threads

### ISSUE THREAD

**Issue by mversic** [asomers/mockall#417]
if you take [this](https://github.com/mversic/rs-odbc) project and run the tests the tests sometimes fail spuriously because of poisoned threads. Also, for example this line gets printed:
```
thread 'handle::test::disconnect_C2' panicked at 'trying to access wrapped value in fragile container from incorrect thread.'
```

This only happens when the tests are run, the code of the library in question is not multi threaded and there are no other dependencies except the `mockall` library. How can we go about investigating the problem?

**Comment by asomers** [comment]
That error message indicates that you used a method like `returning_st` or `withf_st`, presumably because either the return value or argument is non-`Send`.  Even if the library itself is single-threaded, rust's standard test harness uses a thread pool.  Do you have any global variables that get used as arguments to a mock method?  If the global variable gets set by one test, then used by another, that could cause this problem.

**Comment by mversic** [comment]
> That error message indicates that you used a method like returning_st or withf_st, presumably because either the return value or argument is non-Send

I believe this is an accurate description

>  Even if the library itself is single-threaded, rust's standard test harness uses a thread pool

understandable

> Do you have any global variables that get used as arguments to a mock method? If the global variable gets set by one test, then used by another, that could cause this problem.

if by global variable you mean `static` then no, if you mean a `const` then yes. The types used are all `Copy` types.

I'm testing the implementation of `Drop` for a handle(e.g. connection handle) where I expect that the handle has disconnected from the database and called the function to deallocate all the resources. Does this shed any light? The test example is rather simple:

```rs
    #[test]
    fn disconnect_C4() {
        let conn_raw_handle = 13 as SQLHANDLE;

        let SQLDisconnect_ctx = ffi::SQLDisconnect_context();
        let SQLFreeHandle_ctx = ffi::SQLFreeHandle_context();

        SQLDisconnect_ctx
            .expect()
            .once()
            .withf_st(move |x| *x == conn_raw_handle)
            .return_const(SQL_SUCCESS);
        SQLFreeHandle_ctx
            .expect()
            .once()
            .withf_st(move |x, y| *x == SQL_HANDLE_DBC::IDENTIFIER && *y == conn_raw_handle)
            .return_const(SQL_SUCCESS);

        SQLHDBC::<C4, SQL_OV_ODBC3_80> {
            handle: conn_raw_handle,
            parent: PhantomData,
            connected: PhantomData,
            version: PhantomData,
        };
    }
```

**Comment by asomers** [comment]
I see that you're mocking some plain functions.  However, there's no synchronization.  If you set an expectation for `ffi::SQLDisconnect` in one test case, but then call that function from another test case, the second test case may be running in a different thread, causing the "fragile" error.  More seriously, without synchronization, an expectation set by one test case might get satisfied by another.  You need to add a `Mutex` to all test cases that set expectations on a given static method.  See the docs at https://docs.rs/mockall/latest/mockall/#static-methods .

**Comment by mversic** [comment]
oh I see. It's a rather weird design choice to drop Rust's thread-safety guarantees. I appreciate the help

**Comment by asomers** [comment]
It's actually not a violation of any of Rust's guarantees, and it can't be, because it doesn't use any `unsafe` code.  Rust guarantees that multithreaded programs won't experience data races, and Mockall doesn't expose you to data races by mocking static methods.  Each test case is guaranteed to see a whole, intact expectation - it just might be a different thread's expectation.  Rust doesn't guarantee, and can't guarantee, protection from all types of race condition.
BTW, I could've built Mutex protection into the context methods.  That would've prevented problems like yours.  However, I chose not to because it would've created an even worse problem: deadlocks.  And the deadlocks could've been quite surprising to users who didn't even know that mutexes were involved.
