### ISSUE TITLE
Can't cope with constructor pattern?

### ISSUE THREAD

**Issue by michaelmarconi** [asomers/mockall#44]
Hi, your framework looks very promising, however I'm falling at the first hurdle, which is a trait that implements a `new()` constructor:

```
#[cfg(test)]
mod tests {
    use mockall::*;
    use mockall::predicate::*;

    struct Foo {}

    #[automock]
    trait FooTrait {
        fn new() -> Self;
        fn foo(&self) -> String;
    }

    impl FooTrait for Foo {
        fn new() -> Self {
            Foo {}
        }

        fn foo(&self) -> String {
            String::from("I'm SO foo")
        }
    }

    #[test]
    fn test_foo() {
        let mut mock_foo = MockFooTrait::new();
        mock_foo.expect_foo().returning(|| String::from("I'm NOT foo at all"));
        assert_eq!(mock_foo.foo(), "I'm NOT foo at all");
    }
}
```

Yields the following error:
```
thread 'tests::test_foo' panicked at 'No matching expectation found', src/libcore/option.rs:1034:5
```
I've tested it without the constructor and it works perfectly.  Am I missing something obvious here or is the framework currently unable to cope with such a constructor?

**Comment by asomers** [comment]
Yep, you're missing something.  `new` is a static method just like any other, and you need to set an expectation for it.  The confusion stems from the fact that if you hadn't explicitly defined a `new` method, then Mockall would've created one, which *wouldn't* be a regular method, requiring expectations.  If you rename `new` to something else, then the problem will be more obvious.

In this case, you have two easy solutions:
1) In your test, use `MockFooTrait::default` instead of `MockFooTrait::new`, or
2) Create an expectation for the `new` method, like this:
```rust
let ctx = MockFooTrait::new_context();
ctx.expect().returning(|| MockFooTrait::default());
let mut mock_foo = MockFooTrait::new();
```
Hope that helps.

**Comment by michaelmarconi** [comment]
Thanks, that's perfectly clear in retrospect and solves the issue!

The thought had occurred to me but I couldn't see how to create an expectation for `new` before I had created the mock object.  In my case, `default` is a fine solution.
