### ISSUE TITLE
static functions' expectations don't get cleared after a panic.

### ISSUE THREAD

**Issue by DGolubets** [asomers/mockall#442]
I have an issue using mocks for static methods.
I was able to reproduce it with a slight modification of the tests (https://github.com/asomers/mockall/blob/master/mockall/examples/synchronization.rs):
1. Replace `returning` with `return_once`.
2. Change the expectation in the first test to fail it.
3. Now the second test starts to fail with `MockThing::one: Expectation(<anything>) called twice, but it returns by move`

**Comment by asomers** [comment]
This happens because Mockall tries to avoid double-panicing.  If a thread is already panicing, then we don't attempt to verify that all expectations have been satisfied.  However, that has a side effect of not clearing expectations after a panic.  You never would've noticed this behavior if you'd been using the standard Mutex, because subsequent tests would've gotten a PoisonError.  But apparently you're using the unpoisonable Mutex from the example.  I'll fix it.
