### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by DGolubets** [asomers/mockall#45]
Hi,

At the moment with version 0.4 I see error messages like this:
```
panicked at 'No matching expectation found'
```
It would be very helpful to see more details, like a name of the expectation.
Last version of 'mockers' library does very well in this regard. Would be great to have the same here.

**Comment by asomers** [comment]
That particular error message is always accompanied by a useful backtrace.  Is that sufficient for you?  I could add the name of the method, but not the arguments.

**Comment by DGolubets** [comment]
Having the name would be good enough.

I usually run tests with backtracking turned off, for less noise. However
there are many mocked methods in every test, so without a name I have to
guess which mock failed.

Thanks!

**Comment by mgeisler** [comment]
Hi @asomers, I found this issue while experimenting with mockall for to see if I can replace [this mock struct](https://cs.android.com/android/platform/superproject/main/+/main:external/uwb/src/rust/uwb_core/src/uci/mock_uci_manager.rs;l=53;drc=fd81b7d6756feca1cd2218b615b214f924578dfe) with something simpler.

> I could add the name of the method, but not the arguments.

May I ask if there is a fundamental reason which presents printing the arguments (if they implement `Debug`)? Is it perhaps because the macros don't know if an argument implements `Debug`?

I'm coming from [gMock](http://google.github.io/googletest/gmock_cook_book.html#gaining-super-vision-into-mock-calls) where you can get detailed information about mock calls, including their arguments.

As I'm sure you know, mockall instead says something like

```
MockUciManager::session_init(?, ?): No matching expectation found'
```

and I then have to enable the backtrace, find the call site, annotate the arguments with `dbg!` and finally recompile and rerun the test. It would be great if I could skip those steps :slightly_smiling_face:

**Comment by asomers** [comment]
> May I ask if there is a fundamental reason which presents printing the arguments (if they implement `Debug`)? Is it perhaps because the macros don't know if an argument implements `Debug`?

Exactly, @mgeisler .  The macro didn't know if the argument implemented `Debug`.  But this bug is old, and things have changed.  As of Mockall 0.9.1, the macro _does_ know that, _if_ you build Mockall with the **nightly** feature.  In that case, these error messages will include argument values.  And in fact, on the master branch, you don't even need the **nightly** feature.  See PR #425 .
