### ISSUE TITLE
Dependency predicates-tree breaks MSRV

### ISSUE THREAD

**Issue by HampusMat** [asomers/mockall#507]
The MSRV of predicates-tree was changed to 1.64.0 in [this commit](https://github.com/assert-rs/predicates-rs/commit/7a961436d8c2b9cf09e9576a0c9341acb302f49c) and was later released as a patch release as can be seen in [this commit](https://github.com/assert-rs/predicates-rs/commit/4498eef4a2dc4759940e9fe6cc652a6fcff33d57#diff-a1f32c51da122c70ac2ddc1de79aea77fd9c756d529485188b9b63f14dd92dcd).

I came across this problem when trying to test my library crate on Rust 1.63.0.

<s>A temporary fix for this i got to work on my library crate is to manipulate the Cargo dependency resolver to use older versions of predicates-tree and predicates-core
```toml
predicates-tree = "=1.0.7"
predicates-core = "=1.0.5"
```
</s>

The question is if we should
1.  Make Mockall use the latest version of predicates-tree without the 1.64.0 MSRV (1.0.7)
2.  Create a issue in the predicates-rs repository about this asking whether or not the MSRV change can be reverted

**Comment by asomers** [comment]
This is definitely an annoyance.  I've been bitten with it here and on other library crates too.  But it isn't technically a bug.  Mockall 0.11.4 still works in a Rust 1.42.0 project, as long as all of that project's dependencies are suitably old.  Your workaround works well for binary crates, but it's not ideal for library crates.  The problem with library crates is that it prevents your dependents from upgrading to a newer version of predicates-tree, even if they don't care about Rust 1.42.0.

Instead, here's my recommended approach for your library crate:
* Remove those predicates-tree and predicates-core entries from your Cargo.toml
* Do something like `cargo update -p predicates-tree --precise 1.0.7` for as many crates as you need to, so that the build will work locally with your MSRV.
* Save this Cargo.lock file.  `cp Cargo.lock Cargo.lock.msrv; git add Cargo.lock.msrv`
* Tweak your CI setup so that it uses this saved Cargo.lock.msrv file when it's testing on the MSRV.  Here's an example: https://github.com/asomers/mio-aio/commit/9d4836ac9fd5a683ebe345762ef0b2053588b4ae

**Comment by HampusMat** [comment]
I really don't like the idea of having to rename a Cargo lock file to be able to test on Rust 1.63.0. It feels really janky.

I found a solution for dependents being prevented from upgrading to a newer version of predicates-tree with my original fix. Dependants are free to use whatever version of predicates-tree they want if Git is used instead of the crates.io registry in the library crate.
```toml
# predicates 2.13 has predicates-tree 1.0.7
predicates-tree = { git = "https://github.com/assert-rs/predicates-rs", tag = "v2.1.3" }
```

Unfortunely, this can't be used by the Mockall crate as crates.io doesn't allow non dev dependency Git dependencies. Maybe if Cargo has some other way to separate the dev and non dev resolution of a dependency?

**Comment by asomers** [comment]
Well, it does.  You could try adding a `predicates-tree = "=1.0.7"` specification as a dev-dependency in your library crate.  However, that would prevent you from discovering any regressions introduced by newer versions of predicates-tree.  IMHO, that's worse.
I don't like the Cargo.lock.msrv technique either, but I haven't found a better way to do it.  And not for lack of trying.  We went over this big time in the Nix crate.

**Comment by HampusMat** [comment]
I take back my solution for dependents being prevented from upgrading to a newer version of predicates-tree with my original fix. I forgot to test with Mockall also as a dev dependency. It doesn't work then :cry:.

> You could try adding a predicates-tree = "=1.0.7" specification as a dev-dependency in your library crate. 

That's what i meant with my original temporary fix.

**Comment by asomers** [comment]
I suspect that cargo will refuse to publish your crate with that change in place.

**Comment by HampusMat** [comment]
How come? crates.io allows crates to have Git dev-dependencies.

> Note: crates.io does not allow packages to be published with git dependencies (git dev-dependencies are ignored). 

From https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

**Comment by asomers** [comment]
I saw that the predicates-rs issue got closed.  @HampusMat are you satisfied with that solution?

**Comment by HampusMat** [comment]
Oh sorry i forgot to write something about that here. Absolutely. It's much more ergonomic than the Cargo.lock.msrv solution. It really is a shame though that this is not something that can be done in Mockall to prevent future dependants from going through the same headache of all this as i have. Maybe this can be documented? Atleast if you intend to keep the MSRV of 1.60.0

**Comment by asomers** [comment]
No, this really can't be fixed in Mockall.  The only good place to fix it is in Cargo, and I think that they're working on it.  And BTW, the MSRV on the master branch is 1.64.0.
