### ISSUE TITLE
Public visibility of expect_ methods

### ISSUE THREAD

**Issue by krojew** [asomers/mockall#83]
One way to work around #75 is to create a mock! and put it inside a struct which implements async traits and forwards calls to the mock. Unfortunately, even when making the contained mock pub, all expect_* methods are private. It would be great to make them public, hence allowing composition of mocks.

**Comment by asomers** [comment]
A better way to solve #75 would be to first implement #76, and I almost have that working.  But you can also do what you want: just make the mocked function `pub` and then the `expect_` method will also be `pub`.

**Comment by krojew** [comment]
Unfortunately, adding pub breaks the build. Example:

```
mock! {
    Widget {
        pub fn foo();
    }
}
```

> error: expected one of: `const`, `async`, `unsafe`, `extern`, `fn`, `type`, identifier, `self`, `super`, `extern`, `crate`, `::`
> 
>
>        pub fn foo();
>        ^^^

**Comment by asomers** [comment]
Sorry, I didn't read your OP carefully enough.  `pub fn` will work with `#[automock]`.  But if you're using `mock!`, then the `pub` needs to go by the struct's name: `pub Widget`.  That's because `mock!` works a little bit like defining your own trait, and trait methods can't have visibility keywords.

**Comment by asomers** [comment]
Did `pub Widget` work for you?

**Comment by krojew** [comment]
Yes, it did.
